modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/measurements/issues"
license="MIT"

[[mods]]
modId="measurements"
version="${file.jarVersion}"
displayName="Measurements"
displayURL="https://www.curseforge.com/minecraft/mc-mods/measurements"
authors="Mrbysco"
description='''
Measure the distance between positions :)
'''
[[dependencies.measurements]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.measurements]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.0.0-beta,)"
ordering="NONE"
side="BOTH"